baseURL = "https://www.danielschlomer.com/"
languageCode = "en-us"
title = "Daniel Schlomer"
theme = "coder"

[params]
  author = "Daniel Schlomer"
  info = "Software Developer"
  avatarurl = "images/daniel-at-desk.jpg"
  hideCredits = true
  hideCopyright = true
  custom_css = ["css/main.css"]

  [menu]
    [[menu.main]]
      name = "Projects"
      url = "/projects/"

  [[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/daniel-schlomer"
  
  [[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/schlomest"
