baseURL = "https://www.danielschlomer.com/"
languageCode = "en-us"
title = "Daniel Schlomer"
theme = "coder"

[params]
  author = "Daniel Schlomer"
  info = "Software Developer"
  avatarurl = "images/daniel-at-desk.jpg"
  hideCredits = true
  hideCopyright = true
  custom_css = ["css/main.css"]

  [menu]
    [[menu.main]]
      name = "About"
      url = "/about/"

    [[menu.main]]
      name = "Projects"
      url = "/projects/"
